{
 "title": "PPV API Performance",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(ppv_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Latency (avg)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(ppv_http_request_duration_seconds_sum[1m]) / rate(ppv_http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ppv_http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}